/**

 Copyright 2024 University of Denver

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 */

'use strict';

const LOGGER = require('../../libs/log4');
const Base_tasks = require('./tasks_helper');
const FIELDS = require('../../config/exhibit_fields');

/*
 * Publish/suppress operations, generated by Base_tasks.define_publish_ops.
 *
 * `set_grid_item_to_publish` is invoked BY STRING from indexer/model.js
 * (`set_publish_method`), so its name must never change; it has no static
 * call site to catch a rename.
 */
const PUBLISH_OPS = Object.freeze([
    {
        method: 'set_to_publish', table: 'grid_records', status: 1,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Grid records published', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_to_suppress', table: 'grid_records', status: 0,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Grid records suppressed', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_grid_to_publish', table: 'grid_records', status: 1,
        mode: 'single', log: 'Grid record published'
    },
    {
        method: 'set_grid_to_suppress', table: 'grid_records', status: 0,
        mode: 'single', log: 'Grid record suppressed'
    },
    {
        method: 'set_grid_item_to_publish', table: 'grid_item_records', status: 1,
        mode: 'single', log: 'Grid item record published'
    },
    {
        method: 'set_to_publish_grid_items', table: 'grid_item_records', status: 1,
        scope: 'is_member_of_grid', label: 'grid UUID',
        log: 'Grid item records published', log_key: 'grid_uuid'
    },
    {
        method: 'set_to_suppressed_grid_items', table: 'grid_item_records', status: 0,
        scope: 'is_member_of_grid', label: 'grid UUID',
        log: 'Grid item records suppressed', log_key: 'grid_uuid'
    },
    {
        method: 'set_exhibit_grid_items_to_publish', table: 'grid_item_records', status: 1,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Exhibit grid item records published', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_exhibit_grid_items_to_suppress', table: 'grid_item_records', status: 0,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Exhibit grid item records suppressed', log_key: 'exhibit_uuid'
    }
]);

/**
 * Object contains tasks used to manage exhibit grid and grid item records
 * @param DB
 * @param TABLE
 * @type {Exhibit_grid_record_tasks}
 */
const Exhibit_grid_record_tasks = class extends Base_tasks {

    constructor(DB, TABLE) {
        super(DB, TABLE);
    }

    // Shared validation/logging helpers inherited from Base_tasks

    // ==================== GRID-SPECIFIC HELPERS ====================

    /**
     * Sets default values for grid item fields
     * @param {Object} data - Data object to set defaults on
     * @private
     */
    _set_grid_item_defaults(data) {
        this._apply_defaults(data, {
            item_type: 'image',
            type: 'item',
            layout: 'media_top',
            wrap_text: 1,
            media_width: 50,
            media_padding: 1,
            is_alt_text_decorative: 0,
            pdf_open_to_page: 1,
            order: 0,
            is_repo_item: 0,
            is_kaltura_item: 0,
            is_embedded: 0,
            is_published: 0,
            is_locked: 0,
            locked_by_user: 0,
            is_deleted: 0,
            owner: 0
        });
    }

    /**
     * Sets default values for grid fields
     * @param {Object} data - Data object to set defaults on
     * @private
     */
    _set_grid_defaults(data) {
        this._apply_defaults(data, {
            type: 'grid',
            columns: 4,
            order: 0,
            is_published: 0,
            is_deleted: 0,
            owner: 0
        });
    }

    // ==================== COMMON OPERATIONS (overrides) ====================

    /**
     * Generic update publish status for any table
     * @param {string} table_name - Table name
     * @param {Object} where_clause - Where conditions
     * @param {number} status - 0 or 1
     * @param {string} [updated_by=null] - User ID
     * @returns {Promise<Object>} Update result
     * @private
     */
    async _update_publish_status(table_name, where_clause, status, updated_by = null) {
        this._validate_database();
        this._validate_table(table_name);

        if (![0, 1].includes(status)) {
            throw new Error('Status must be 0 or 1');
        }

        // Check existing records
        const existing_count = await this.DB(this.TABLE[table_name])
            .count('id as count')
            .where({
                ...where_clause,
                is_deleted: 0
            })
            .timeout(this.QUERY_TIMEOUT);

        const total_records = existing_count?.[0]?.count ? parseInt(existing_count[0].count, 10) : 0;

        if (total_records === 0) {
            return {
                success: true,
                affected_rows: 0,
                total_records: 0,
                message: `No records found to ${status === 1 ? 'publish' : 'suppress'}`
            };
        }

        const update_data = {
            is_published: status,
            updated: this.DB.fn.now()
        };

        if (updated_by) {
            update_data.updated_by = updated_by;
        }

        const affected_rows = await this.DB(this.TABLE[table_name])
            .where({
                ...where_clause,
                is_deleted: 0
            })
            .update(update_data)
            .timeout(this.QUERY_TIMEOUT);

        return {
            success: true,
            affected_rows,
            total_records,
            status: status === 1 ? 'published' : 'suppressed',
            updated_by,
            message: `${affected_rows} record(s) ${status === 1 ? 'published' : 'suppressed'} successfully`
        };
    }

    /**
     * Generic update single record publish status
     * @param {string} table_name - Table name
     * @param {string} uuid - Record UUID
     * @param {number} status - 0 or 1
     * @param {string} [updated_by=null] - User ID
     * @returns {Promise<Object>} Update result
     * @private
     */
    async _update_single_publish_status(table_name, uuid, status, updated_by = null) {
        this._validate_database();
        this._validate_table(table_name);

        const uuid_trimmed = this._validate_uuid(uuid, `${table_name} UUID`);

        if (![0, 1].includes(status)) {
            throw new Error('Status must be 0 or 1');
        }

        // Check if record exists
        const existing = await this.DB(this.TABLE[table_name])
            .select('id', 'uuid', 'is_published', 'is_deleted')
            .where({uuid: uuid_trimmed})
            .first()
            .timeout(this.QUERY_TIMEOUT);

        if (!existing) {
            throw new Error(`${table_name} record not found`);
        }

        if (existing.is_deleted === 1) {
            throw new Error(`Cannot ${status === 1 ? 'publish' : 'suppress'} deleted ${table_name} record`);
        }

        if (existing.is_published === status) {
            return {
                success: true,
                already_set: true,
                uuid: uuid_trimmed,
                message: `${table_name} was already ${status === 1 ? 'published' : 'suppressed'}`
            };
        }

        const update_data = {
            is_published: status,
            updated: this.DB.fn.now()
        };

        if (updated_by) {
            update_data.updated_by = updated_by;
        }

        const affected_rows = await this.DB(this.TABLE[table_name])
            .where({
                uuid: uuid_trimmed,
                is_deleted: 0
            })
            .update(update_data)
            .timeout(this.QUERY_TIMEOUT);

        if (affected_rows === 0) {
            throw new Error(`Failed to ${status === 1 ? 'publish' : 'suppress'} ${table_name} record: No rows affected`);
        }

        return {
            success: true,
            uuid: uuid_trimmed,
            affected_rows,
            updated_by,
            message: `${table_name} record ${status === 1 ? 'published' : 'suppressed'} successfully`
        };
    }

    // ==================== GRID RECORDS ====================

    /**
     * Creates a new grid record in the database
     * @param {Object} data - Grid record data
     * @param {string} [created_by=null] - User ID creating the record
     * @returns {Promise<Object>} Created grid record with ID
     */
    async create_grid_record(data, created_by = null) {

        // `internal_name` is dashboard-only: stored and listed, never indexed.
        const ALLOWED_FIELDS = FIELDS.GRID_CREATE_FIELDS;

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('grid_records');

            const {sanitized_data} = this._sanitize_data(data, ALLOWED_FIELDS);

            if (Object.keys(sanitized_data).length === 0) {
                throw new Error('No valid fields provided for insert');
            }

            // Set defaults
            this._set_grid_defaults(sanitized_data);

            // Add timestamps and metadata
            sanitized_data.created = this.DB.fn.now();
            sanitized_data.updated = this.DB.fn.now();

            if (created_by) {
                sanitized_data.created_by = created_by;
                sanitized_data.updated_by = created_by;
            }

            /* Read-back now goes through the shared helper, which selects '*'
             * explicitly. This copy relied on the implicit SELECT *; same rows. */
            return await this._insert_and_fetch(
                'grid_records',
                sanitized_data,
                {
                    log_message: 'Grid record created successfully',
                    log_context: {created_by}
                }
            );

        } catch (error) {
            this._handle_error(error, 'create_grid_record', {
                data_keys: Object.keys(data || {}),
                created_by
            });
        }
    }

    /**
     * Gets all grid records by exhibit
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @returns {Promise<Array>} Array of grid records
     */
    async get_grid_records(is_member_of_exhibit) {

        try {

            this._validate_database();
            this._validate_table('grid_records');

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            const results = await this.DB(this.TABLE.grid_records)
                .select('*')
                .where({
                    is_member_of_exhibit: exhibit_uuid,
                    is_deleted: 0
                })
                .orderBy('order', 'asc')
                .timeout(this.QUERY_TIMEOUT);

            return results || [];

        } catch (error) {
            this._handle_error(error, 'get_grid_records', {
                is_member_of_exhibit
            });
        }
    }

    /**
     * Gets a single grid record by exhibit and grid UUID
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} grid_id - The grid UUID
     * @returns {Promise<Object|null>} Grid record or null
     */
    async get_grid_record(is_member_of_exhibit, grid_id) {

        try {

            this._validate_database();
            this._validate_table('grid_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [grid_id]: 'grid UUID'
            });

            const record = await this.DB(this.TABLE.grid_records)
                .select('*')
                .where({
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['grid UUID'],
                    is_deleted: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Grid record not found', validated);
                return null;
            }

            this._log_success('Grid record retrieved', {
                uuid: validated['grid UUID']
            });

            return record;

        } catch (error) {
            this._handle_error(error, 'get_grid_record', {
                is_member_of_exhibit,
                grid_id
            });
        }
    }

    /**
     * Updates a grid record
     *
     * NOT routed through Base_tasks._update_scoped, unlike its five siblings:
     * this one resolves true/false instead of throwing, does no exists check,
     * and grid_model reads `result === false` to raise a 500. Three task tests
     * and one model test pin that boolean contract, and grid_model is owned
     * elsewhere, so the drift is left standing rather than half-fixed.
     *
     * @param {Object} data - Grid data to update
     * @returns {Promise<boolean>} Update success status
     */
    async update_grid_record(data) {

        // `internal_name` is dashboard-only: stored and listed, never indexed.
        const UPDATABLE_FIELDS = FIELDS.GRID_UPDATE_FIELDS;

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('grid_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'grid UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            const {sanitized_data} = this._sanitize_data(
                data,
                UPDATABLE_FIELDS,
                ['uuid', 'is_member_of_exhibit']
            );

            if (Object.keys(sanitized_data).length === 0) {
                LOGGER.module().error('No valid fields to update');
                return false;
            }

            const rows_affected = await this.DB(this.TABLE.grid_records)
                .where({
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['grid UUID'],
                    is_deleted: 0
                })
                .update(sanitized_data)
                .timeout(this.QUERY_TIMEOUT);

            if (rows_affected === 0) {
                LOGGER.module().warn('No grid record found or updated');
                return false;
            }

            this._log_success('Grid record updated successfully', {
                uuid: validated['grid UUID']
            });

            return true;

        } catch (error) {
            this._handle_error(error, 'update_grid_record', {
                uuid: data?.uuid
            });
        }
    }

    /**
     * Gets the count of grid records for an exhibit
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {Object} [options={}] - Count options
     * @returns {Promise<number>} Count of grid records
     */
    async get_record_count(is_member_of_exhibit, options = {}) {

        const {
            include_deleted = false,
            include_unpublished = true
        } = options;

        try {

            this._validate_database();
            this._validate_table('grid_records');

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            const where_clause = {is_member_of_exhibit: exhibit_uuid};

            if (!include_deleted) {
                where_clause.is_deleted = 0;
            }

            if (!include_unpublished) {
                where_clause.is_published = 1;
            }

            const count = await this._get_record_count('grid_records', where_clause);

            this._log_success('Grid record count retrieved', {
                is_member_of_exhibit: exhibit_uuid,
                count
            });

            return count;

        } catch (error) {
            this._handle_error(error, 'get_grid_record_count', {
                is_member_of_exhibit
            });
        }
    }

    // ==================== GRID ITEM RECORDS ====================

    /**
     * Gets all grid item records for a grid
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_grid - The grid UUID
     * @returns {Promise<Array>} Array of grid item records
     */
    async get_grid_item_records(is_member_of_exhibit, is_member_of_grid) {

        try {

            this._validate_database();
            this._validate_table('grid_item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_grid]: 'grid UUID'
            });

            const records = await this._with_media_library(
                this.DB(this.TABLE.grid_item_records), 'grid_item_records', 'list'
            )
                .where({
                    [`${this.TABLE.grid_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.grid_item_records}.is_member_of_grid`]: validated['grid UUID'],
                    [`${this.TABLE.grid_item_records}.is_deleted`]: 0
                })
                .orderBy(`${this.TABLE.grid_item_records}.order`, 'asc')
                .timeout(this.QUERY_TIMEOUT);

            this._log_success('Grid item records retrieved', {
                ...validated,
                count: records.length
            });

            return records || [];

        } catch (error) {
            this._handle_error(error, 'get_grid_item_records', {
                is_member_of_exhibit,
                is_member_of_grid
            });
        }
    }

    /**
     * Gets the count of grid item records for a grid
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_grid - The grid UUID
     * @param {Object} [options={}] - Count options
     * @param {boolean} [options.published_only=false] - Count only published items
     * @returns {Promise<number>} Count of grid item records
     */
    async get_grid_item_count(is_member_of_exhibit, is_member_of_grid, options = {}) {

        const {published_only = false} = options;

        try {

            this._validate_database();
            this._validate_table('grid_item_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_grid]: 'grid UUID'
            });

            const where_clause = {
                is_member_of_exhibit: validated['exhibit UUID'],
                is_member_of_grid: validated['grid UUID'],
                is_deleted: 0
            };

            if (published_only) {
                where_clause.is_published = 1;
            }

            const count = await this._get_record_count('grid_item_records', where_clause);

            this._log_success('Grid item count retrieved', {
                ...validated,
                published_only,
                count
            });

            return count;

        } catch (error) {
            this._handle_error(error, 'get_grid_item_count', {
                is_member_of_exhibit,
                is_member_of_grid
            });
        }
    }

    /**
     * Creates a new grid item record
     * @param {Object} data - Grid item record data
     * @param {string} [created_by=null] - User ID creating the record
     * @returns {Promise<Object>} Created grid item record
     */
    async create_grid_item_record(data, created_by = null) {

        /*
         * Lock and recycle-bin state (`is_locked`, `locked_by_user`,
         * `locked_at`, `is_deleted`) is owned by the server; a create request
         * must not be able to set it. The whitelist lives in
         * config/exhibit_fields.js so that rule is auditable in one place;
         * defaults are applied below.
         */
        const ALLOWED_FIELDS = FIELDS.GRID_ITEM_CREATE_FIELDS;

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('grid_item_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'grid item UUID',
                [data.is_member_of_grid]: 'grid UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            const {sanitized_data} = this._sanitize_data(data, ALLOWED_FIELDS);

            // Set defaults
            this._set_grid_item_defaults(sanitized_data);

            if (created_by) {
                sanitized_data.created_by = created_by;
                sanitized_data.updated_by = created_by;
            }

            const created_record = await this._insert_and_fetch(
                'grid_item_records',
                sanitized_data,
                {
                    log_message: 'Grid item record created successfully',
                    log_context: {created_by}
                }
            );

            return {
                success: true,
                id: created_record.id,
                uuid: created_record.uuid,
                record: created_record,
                message: 'Grid item record created successfully'
            };

        } catch (error) {
            this._handle_error(error, 'create_grid_item_record', {
                uuid: data?.uuid,
                created_by
            });
        }
    }

    /**
     * Gets a single grid item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} grid_id - The grid UUID
     * @param {string} item_id - The item UUID
     * @returns {Promise<Object|null>} Grid item record or null
     */
    async get_grid_item_record(is_member_of_exhibit, grid_id, item_id) {

        try {

            this._validate_database();
            this._validate_table('grid_item_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [grid_id]: 'grid UUID',
                [item_id]: 'item UUID'
            });

            const record = await this.DB(this.TABLE.grid_item_records)
                .select('*')
                .where({
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_grid: validated['grid UUID'],
                    uuid: validated['item UUID'],
                    is_deleted: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Grid item record not found', validated);
                return null;
            }

            this._log_success('Grid item record retrieved', {
                uuid: validated['item UUID']
            });

            return record;

        } catch (error) {
            this._handle_error(error, 'get_grid_item_record', {
                is_member_of_exhibit,
                grid_id,
                item_id
            });
        }
    }

    /**
     * Gets a grid item record for editing and locks it
     * @param {string|number} uid - User ID
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} grid_id - The grid UUID
     * @param {string} item_id - The item UUID
     * @returns {Promise<Object|null>} Grid item record with lock status
     */
    async get_grid_item_edit_record(uid, is_member_of_exhibit, grid_id, item_id) {

        try {

            this._validate_database();
            this._validate_table('grid_item_records');
            this._validate_table('media_library_records');

            this._validate_user_id(uid);

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [grid_id]: 'grid UUID',
                [item_id]: 'item UUID'
            });

            const record = await this._with_media_library(
                this.DB(this.TABLE.grid_item_records), 'grid_item_records', 'edit'
            )
                .where({
                    [`${this.TABLE.grid_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.grid_item_records}.is_member_of_grid`]: validated['grid UUID'],
                    [`${this.TABLE.grid_item_records}.uuid`]: validated['item UUID'],
                    [`${this.TABLE.grid_item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Grid item record not found', validated);
                return null;
            }

            return await this._lock_for_edit(record, uid, 'grid_item_records', {
                label: 'Grid item',
                uuid: validated['item UUID'],
                id_key: 'item_id'
            });

        } catch (error) {
            this._handle_error(error, 'get_grid_item_edit_record', {
                uid,
                item_id
            });
        }
    }

    /**
     * Gets a grid item record with media library metadata for read-only details view.
     * Same query as get_grid_item_edit_record but does NOT lock the record.
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} grid_id - The grid UUID
     * @param {string} item_id - The item UUID
     * @returns {Promise<Object|null>} Grid item record with media metadata or null
     */
    async get_grid_item_details_record(is_member_of_exhibit, grid_id, item_id) {

        try {

            this._validate_database();
            this._validate_table('grid_item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [grid_id]: 'grid UUID',
                [item_id]: 'item UUID'
            });

            const record = await this._with_media_library(
                this.DB(this.TABLE.grid_item_records), 'grid_item_records', 'edit'
            )
                .where({
                    [`${this.TABLE.grid_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.grid_item_records}.is_member_of_grid`]: validated['grid UUID'],
                    [`${this.TABLE.grid_item_records}.uuid`]: validated['item UUID'],
                    [`${this.TABLE.grid_item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Grid item record not found', validated);
                return null;
            }

            this._log_success('Grid item details record retrieved successfully', {
                uuid: validated['item UUID'],
                is_member_of_exhibit: validated['exhibit UUID'],
                is_member_of_grid: validated['grid UUID']
            });

            return record;

        } catch (error) {
            this._handle_error(error, 'get_grid_item_details_record', {
                is_member_of_exhibit,
                grid_id,
                item_id
            });
        }
    }

    /**
     * Updates a grid item record
     * @param {Object} data - Grid item data to update
     * @param {string} [updated_by=null] - User ID performing the update
     * @returns {Promise<Object>} Update result
     */
    async update_grid_item_record(data, updated_by = null) {

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('grid_item_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'grid item UUID',
                [data.is_member_of_grid]: 'grid UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            return await this._update_scoped(
                'grid_item_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_grid: validated['grid UUID'],
                    uuid: validated['grid item UUID']
                },
                data,
                {
                    allowed_fields: FIELDS.CONTAINER_ITEM_UPDATE_FIELDS,
                    skip_fields: ['uuid', 'is_member_of_grid', 'is_member_of_exhibit'],
                    label: 'Grid item',
                    uuid: validated['grid item UUID'],
                    updated_by,
                    select_fields: ['id', 'uuid', 'is_deleted', 'is_locked', 'locked_by_user'],
                    warn_when_locked: true
                }
            );

        } catch (error) {
            this._handle_error(error, 'update_grid_item_record', {
                uuid: data?.uuid,
                updated_by
            });
        }
    }

    /**
     * Soft deletes a grid item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} grid_id - The grid UUID
     * @param {string} grid_item_id - The grid item UUID
     * @param {string} [deleted_by=null] - User ID performing the deletion
     * @returns {Promise<Object>} Delete result
     */
    async delete_grid_item_record(is_member_of_exhibit, grid_id, grid_item_id, deleted_by = null) {

        try {

            this._validate_database();
            this._validate_table('grid_item_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [grid_id]: 'grid UUID',
                [grid_item_id]: 'grid item UUID'
            });

            const {already_deleted, affected_rows} = await this._soft_delete_scoped(
                'grid_item_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_grid: validated['grid UUID'],
                    uuid: validated['grid item UUID']
                },
                {
                    label: 'Grid item',
                    deleted_by,
                    select_fields: ['id', 'uuid', 'title', 'is_deleted']
                }
            );

            if (already_deleted) {
                return {
                    success: true,
                    already_deleted: true,
                    grid_item_id: validated['grid item UUID'],
                    message: 'Grid item was already deleted'
                };
            }

            this._log_success('Grid item record deleted successfully', {
                grid_item_id: validated['grid item UUID'],
                affected_rows,
                deleted_by
            });

            return {
                success: true,
                grid_item_id: validated['grid item UUID'],
                affected_rows,
                deleted_by,
                message: 'Grid item record deleted successfully'
            };

        } catch (error) {
            this._handle_error(error, 'delete_grid_item_record', {
                is_member_of_exhibit,
                grid_id,
                grid_item_id,
                deleted_by
            });
        }
    }

    /*
     * ==================== PUBLISHING / SUPPRESSING ====================
     *
     * The nine publish/suppress methods are generated from PUBLISH_OPS at the
     * top of this file. All nine resolve the result object and throw via
     * _handle_error, exactly as before. The grid overrides of
     * _update_publish_status / _update_single_publish_status above still
     * apply — the generator calls whichever the instance resolves.
     */

    // ==================== REORDERING ====================

    /**
     * Reorders grids
     * @param {string} is_member_of_exhibit - Exhibit UUID
     * @param {Object} grids - Grid object with uuid and order
     * @returns {Promise<boolean>} Reorder success status
     */
    async reorder_grids(is_member_of_exhibit, grids) {

        try {

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            await this._reorder_items(
                'grid_records',
                {is_member_of_exhibit: exhibit_uuid},
                grids
            );

            this._log_success('Grid reordered', {
                exhibit_uuid,
                uuid: grids.uuid,
                order: grids.order
            });

            return true;

        } catch (error) {
            this._handle_error(error, 'reorder_grids', {
                is_member_of_exhibit
            });
        }
    }

    /**
     * Reorders grid items
     * @param {string} is_member_of_grid - Grid UUID
     * @param {Object} grids - Grid item object with uuid and order
     * @returns {Promise<boolean>} Reorder success status
     */
    async reorder_grid_items(is_member_of_grid, grids) {

        try {

            const grid_uuid = this._validate_uuid(is_member_of_grid, 'grid UUID');
            await this._reorder_items(
                'grid_item_records',
                {is_member_of_grid: grid_uuid},
                grids
            );

            this._log_success('Grid item reordered', {
                grid_uuid,
                uuid: grids.uuid,
                order: grids.order
            });

            return true;

        } catch (error) {
            this._handle_error(error, 'reorder_grid_items', {
                is_member_of_grid
            });
        }
    }
};

Base_tasks.define_publish_ops(Exhibit_grid_record_tasks, PUBLISH_OPS);

module.exports = Exhibit_grid_record_tasks;
