/**

 Copyright 2024 University of Denver

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 */

'use strict';

const Base_tasks = require('./tasks_helper');
const FIELDS = require('../../config/exhibit_fields');

/*
 * Publish/suppress operations, generated by Base_tasks.define_publish_ops.
 *
 * `set_timeline_item_to_publish` is invoked BY STRING from indexer/model.js
 * (`set_publish_method`), so its name must never change; it has no static
 * call site to catch a rename.
 *
 * Note the timeline class routes even its single-record toggles through the
 * BULK helper with a `{uuid}` scope — grid uses _update_single_publish_status
 * for the same job. The difference matters: the bulk helper skips the exists /
 * already-published guards the single one applies.
 */
const PUBLISH_OPS = Object.freeze([
    {
        method: 'set_to_publish', table: 'timeline_records', status: 1,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Timeline is_published set', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_to_suppress', table: 'timeline_records', status: 0,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Timeline is_published suppressed', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_timeline_to_publish', table: 'timeline_records', status: 1,
        scope: 'uuid', label: 'timeline UUID',
        log: 'Timeline is_published set', log_key: 'timeline_uuid'
    },
    {
        method: 'set_timeline_to_suppress', table: 'timeline_records', status: 0,
        scope: 'uuid', label: 'timeline UUID',
        log: 'Timeline is_published suppressed', log_key: 'timeline_uuid'
    },
    {
        method: 'set_timeline_item_to_publish', table: 'timeline_item_records', status: 1,
        scope: 'uuid', label: 'timeline item UUID',
        log: 'Timeline item is_published set', log_key: 'item_uuid'
    },
    {
        method: 'set_to_publish_timeline_items', table: 'timeline_item_records', status: 1,
        scope: 'is_member_of_timeline', label: 'timeline UUID',
        log: 'Timeline items is_published set', log_key: 'timeline_uuid'
    },
    {
        method: 'set_to_suppressed_timeline_items', table: 'timeline_item_records', status: 0,
        scope: 'is_member_of_timeline', label: 'timeline UUID',
        log: 'Timeline items is_published suppressed', log_key: 'timeline_uuid'
    },
    {
        method: 'set_exhibit_timeline_items_to_publish', table: 'timeline_item_records', status: 1,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Exhibit timeline item records published', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_exhibit_timeline_items_to_suppress', table: 'timeline_item_records', status: 0,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Exhibit timeline item records suppressed', log_key: 'exhibit_uuid'
    }
]);

/**
 * Object contains tasks used to manage exhibit timeline records
 * @param DB
 * @param TABLE
 * @type {Exhibit_timeline_record_tasks}
 */
const Exhibit_timeline_record_tasks = class extends Base_tasks {

    constructor(DB, TABLE) {
        super(DB, TABLE);
    }

    // Shared methods inherited from Base_tasks

    // ==================== TIMELINE RECORDS ====================

    /**
     * Creates a new timeline record in the database
     * @param {Object} data - Timeline record data
     * @param {string} data.uuid - Timeline UUID (required)
     * @param {string} data.is_member_of_exhibit - Exhibit UUID (required)
     * @param {string} [created_by=null] - User ID creating the record
     * @returns {Promise<Object>} Created timeline record with ID
     * @throws {Error} If validation fails or creation fails
     */
    async create_timeline_record(data, created_by = null) {

        // `title` intentionally omitted — dropped from tbl_timelines by the
        // titles-to-subheadings migration (timeline containers no longer carry a title).
        // `internal_name` is dashboard-only: stored and listed, never indexed.
        const ALLOWED_FIELDS = FIELDS.TIMELINE_CREATE_FIELDS;

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('timeline_records');

            // Validate required fields
            const validated_uuids = this._validate_uuids({
                [data.uuid]: 'timeline UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            // Sanitize data
            const {sanitized_data} = this._sanitize_data(data, ALLOWED_FIELDS);

            // Set defaults
            this._apply_defaults(sanitized_data, {
                type: 'vertical_timeline',
                order: 0,
                is_deleted: 0,
                is_published: 0,
                owner: 0
            });

            if (created_by) {
                sanitized_data.created_by = created_by;
                sanitized_data.updated_by = created_by;
            }

            // Insert in transaction
            const created_record = await this._insert_and_fetch(
                'timeline_records',
                sanitized_data,
                {
                    log_message: 'Timeline record created successfully',
                    log_context: {created_by}
                }
            );

            return {
                success: true,
                id: created_record.id,
                uuid: created_record.uuid,
                record: created_record,
                message: 'Timeline record created successfully'
            };

        } catch (error) {
            this._handle_error(error, 'create_timeline_record', {
                uuid: data?.uuid,
                exhibit_uuid: data?.is_member_of_exhibit,
                created_by
            });
        }
    }

    /**
     * Gets all timeline records by exhibit
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @returns {Promise<Array>} Array of timeline records
     */
    async get_timeline_records(is_member_of_exhibit) {

        try {

            this._validate_database();
            this._validate_table('timeline_records');

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            const timeline_records = await this.DB(this.TABLE.timeline_records)
                .select('*')
                .where({
                    is_member_of_exhibit: exhibit_uuid,
                    is_deleted: 0
                })
                .orderBy('order', 'asc')
                .timeout(this.QUERY_TIMEOUT);

            this._log_success('Timeline records retrieved successfully', {
                is_member_of_exhibit: exhibit_uuid,
                count: timeline_records.length
            });

            return timeline_records;

        } catch (error) {
            this._handle_error(error, 'get_timeline_records', {
                is_member_of_exhibit
            });
        }
    }

    /**
     * Gets a single timeline record by exhibit and timeline UUID
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} timeline_uuid - The timeline UUID
     * @returns {Promise<Object|null>} Timeline record or null if not found
     */
    async get_timeline_record(is_member_of_exhibit, timeline_uuid) {

        try {

            this._validate_database();
            this._validate_table('timeline_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [timeline_uuid]: 'timeline UUID'
            });

            const timeline_record = await this.DB(this.TABLE.timeline_records)
                .select('*')
                .where({
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['timeline UUID'],
                    is_deleted: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!timeline_record) {
                this._log_success('Timeline record not found', validated);
                return null;
            }

            this._log_success('Timeline record retrieved successfully', {
                uuid: timeline_record.uuid,
            });

            return timeline_record;

        } catch (error) {
            this._handle_error(error, 'get_timeline_record', {
                is_member_of_exhibit,
                timeline_uuid
            });
        }
    }

    /**
     * Updates a timeline record in the database
     * @param {Object} data - Timeline data to update
     * @param {string} [updated_by=null] - User ID performing the update
     * @returns {Promise<Object>} Update result
     */
    async update_timeline_record(data, updated_by = null) {

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('timeline_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'timeline UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            return await this._update_scoped(
                'timeline_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['timeline UUID']
                },
                data,
                {
                    /* `internal_name` is dashboard-only: stored and listed, never indexed. */
                    allowed_fields: FIELDS.TIMELINE_UPDATE_FIELDS,
                    skip_fields: ['uuid', 'is_member_of_exhibit'],
                    label: 'Timeline',
                    uuid: validated['timeline UUID'],
                    updated_by
                }
            );

        } catch (error) {
            this._handle_error(error, 'update_timeline_record', {
                uuid: data?.uuid,
                updated_by
            });
        }
    }

    // ==================== TIMELINE ITEM RECORDS ====================

    /**
     * Gets all timeline item records by exhibit and timeline
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_timeline - The timeline UUID
     * @returns {Promise<Array>} Array of timeline item records
     */
    async get_timeline_item_records(is_member_of_exhibit, is_member_of_timeline) {

        try {

            this._validate_database();
            this._validate_table('timeline_item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_timeline]: 'timeline UUID'
            });

            const timeline_items = await this._with_media_library(
                this.DB(this.TABLE.timeline_item_records), 'timeline_item_records', 'list'
            )
                .where({
                    [`${this.TABLE.timeline_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.timeline_item_records}.is_member_of_timeline`]: validated['timeline UUID'],
                    [`${this.TABLE.timeline_item_records}.is_deleted`]: 0
                })
                .orderBy(`${this.TABLE.timeline_item_records}.order`, 'asc')
                .timeout(this.QUERY_TIMEOUT);

            this._log_success('Timeline item records retrieved successfully', {
                ...validated,
                count: timeline_items.length
            });

            return timeline_items;

        } catch (error) {
            this._handle_error(error, 'get_timeline_item_records', {
                is_member_of_exhibit,
                is_member_of_timeline
            });
        }
    }

    /**
     * Creates a new timeline item record
     * @param {Object} data - Timeline item record data
     * @param {string} [created_by=null] - User ID creating the record
     * @returns {Promise<Object>} Created timeline item record
     */
    async create_timeline_item_record(data, created_by = null) {

        /*
         * Lock and recycle-bin state (`is_locked`, `locked_by_user`,
         * `locked_at`, `is_deleted`) is owned by the server; a create request
         * must not be able to set it. The whitelist lives in
         * config/exhibit_fields.js so that rule is auditable in one place;
         * defaults are applied below.
         */
        const ALLOWED_FIELDS = FIELDS.TIMELINE_ITEM_CREATE_FIELDS;

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('timeline_item_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'timeline item UUID',
                [data.is_member_of_timeline]: 'timeline UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            const {sanitized_data} = this._sanitize_data(data, ALLOWED_FIELDS);

            // Set defaults based on schema
            this._apply_defaults(sanitized_data, {
                item_type: 'image',
                type: 'item',
                layout: 'media_top',
                wrap_text: 1,
                media_width: 50,
                media_padding: 1,
                is_alt_text_decorative: 0,
                pdf_open_to_page: 1,
                order: 0,
                is_repo_item: 0,
                is_kaltura_item: 0,
                is_embedded: 0,
                is_published: 0,
                is_locked: 0,
                locked_by_user: 0,
                is_deleted: 0,
                owner: 0
            });

            if (created_by) {
                sanitized_data.created_by = created_by;
                sanitized_data.updated_by = created_by;
            }

            const created_record = await this._insert_and_fetch(
                'timeline_item_records',
                sanitized_data,
                {
                    log_message: 'Timeline item record created successfully',
                    log_context: (record) => ({title: record.title, created_by})
                }
            );

            return {
                success: true,
                id: created_record.id,
                uuid: created_record.uuid,
                record: created_record,
                message: 'Timeline item record created successfully'
            };

        } catch (error) {
            this._handle_error(error, 'create_timeline_item_record', {
                uuid: data?.uuid,
                created_by
            });
        }
    }

    /**
     * Gets a single timeline item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_timeline - The timeline UUID
     * @param {string} item_uuid - The timeline item UUID
     * @returns {Promise<Object|null>} Timeline item record or null
     */
    async get_timeline_item_record(is_member_of_exhibit, is_member_of_timeline, item_uuid) {

        try {

            this._validate_database();
            this._validate_table('timeline_item_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_timeline]: 'timeline UUID',
                [item_uuid]: 'timeline item UUID'
            });

            const timeline_item = await this.DB(this.TABLE.timeline_item_records)
                .select('*')
                .where({
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_timeline: validated['timeline UUID'],
                    uuid: validated['timeline item UUID'],
                    is_deleted: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!timeline_item) {
                this._log_success('Timeline item record not found', validated);
                return null;
            }

            this._log_success('Timeline item record retrieved successfully', {
                uuid: timeline_item.uuid,
                title: timeline_item.title
            });

            return timeline_item;

        } catch (error) {
            this._handle_error(error, 'get_timeline_item_record', {
                is_member_of_exhibit,
                is_member_of_timeline,
                item_uuid
            });
        }
    }

    /**
     * Gets a timeline item record for editing and locks it
     * @param {string} user_id - The user ID
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_timeline - The timeline UUID
     * @param {string} item_uuid - The timeline item UUID
     * @returns {Promise<Object>} Timeline item record with lock information
     */
    async get_timeline_item_edit_record(user_id, is_member_of_exhibit, is_member_of_timeline, item_uuid) {

        try {

            this._validate_database();
            this._validate_table('timeline_item_records');
            this._validate_table('media_library_records');

            /*
             * The shared validator accepts a user_id in either string or
             * numeric form. lock_record must still get a string.
             */
            const user_id_trimmed = String(this._validate_user_id(user_id));
            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_timeline]: 'timeline UUID',
                [item_uuid]: 'timeline item UUID'
            });

            const timeline_item = await this._with_media_library(
                this.DB(this.TABLE.timeline_item_records), 'timeline_item_records', 'timeline_edit'
            )
                .where({
                    [`${this.TABLE.timeline_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.timeline_item_records}.is_member_of_timeline`]: validated['timeline UUID'],
                    [`${this.TABLE.timeline_item_records}.uuid`]: validated['timeline item UUID'],
                    [`${this.TABLE.timeline_item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!timeline_item) {
                throw new Error('Timeline item record not found');
            }

            /* Timeline items are the one type that refuses to hand over a
             * record another user holds, rather than logging and returning it. */
            return await this._lock_for_edit(timeline_item, user_id_trimmed, 'timeline_item_records', {
                label: 'Timeline item',
                uuid: validated['timeline item UUID'],
                id_key: 'item_id',
                throw_when_locked_by_other: true
            });

        } catch (error) {
            this._handle_error(error, 'get_timeline_item_edit_record', {
                user_id,
                item_uuid
            });
        }
    }

    /**
     * Gets a timeline item record for the details (read-only) view.
     * Performs the same media-library JOINs as get_timeline_item_edit_record
     * but does NOT lock the record.
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_timeline - The timeline UUID
     * @param {string} item_uuid - The timeline item UUID
     * @returns {Promise<Object>} Timeline item record with media library metadata
     */
    async get_timeline_item_details_record(is_member_of_exhibit, is_member_of_timeline, item_uuid) {

        try {

            this._validate_database();
            this._validate_table('timeline_item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_timeline]: 'timeline UUID',
                [item_uuid]: 'timeline item UUID'
            });

            const timeline_item = await this._with_media_library(
                this.DB(this.TABLE.timeline_item_records), 'timeline_item_records', 'timeline_edit'
            )
                .where({
                    [`${this.TABLE.timeline_item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.timeline_item_records}.is_member_of_timeline`]: validated['timeline UUID'],
                    [`${this.TABLE.timeline_item_records}.uuid`]: validated['timeline item UUID'],
                    [`${this.TABLE.timeline_item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!timeline_item) {
                throw new Error('Timeline item record not found');
            }

            this._log_success('Timeline item details record retrieved successfully', {
                uuid: timeline_item.uuid,
                title: timeline_item.title
            });

            return timeline_item;

        } catch (error) {
            this._handle_error(error, 'get_timeline_item_details_record', {
                is_member_of_exhibit,
                is_member_of_timeline,
                item_uuid
            });
        }
    }

    /**
     * Updates a timeline item record
     * @param {Object} data - Timeline item data to update
     * @param {string} [updated_by=null] - User ID performing the update
     * @returns {Promise<Object>} Update result
     */
    async update_timeline_item_record(data, updated_by = null) {

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('timeline_item_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'timeline item UUID',
                [data.is_member_of_timeline]: 'timeline UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            return await this._update_scoped(
                'timeline_item_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_timeline: validated['timeline UUID'],
                    uuid: validated['timeline item UUID']
                },
                data,
                {
                    allowed_fields: FIELDS.CONTAINER_ITEM_UPDATE_FIELDS,
                    skip_fields: ['uuid', 'is_member_of_timeline', 'is_member_of_exhibit'],
                    label: 'Timeline item',
                    uuid: validated['timeline item UUID'],
                    updated_by,
                    select_fields: ['id', 'uuid', 'is_deleted', 'is_locked', 'locked_by_user'],
                    warn_when_locked: true
                }
            );

        } catch (error) {
            this._handle_error(error, 'update_timeline_item_record', {
                uuid: data?.uuid,
                updated_by
            });
        }
    }

    /**
     * Soft deletes a timeline item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} is_member_of_timeline - The timeline UUID
     * @param {string} item_uuid - The timeline item UUID
     * @param {string} [deleted_by=null] - User ID performing the deletion
     * @returns {Promise<Object>} Delete result
     */
    async delete_timeline_item_record(is_member_of_exhibit, is_member_of_timeline, item_uuid, deleted_by = null) {

        try {

            this._validate_database();
            this._validate_table('timeline_item_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [is_member_of_timeline]: 'timeline UUID',
                [item_uuid]: 'timeline item UUID'
            });

            const {already_deleted, existing, affected_rows} = await this._soft_delete_scoped(
                'timeline_item_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    is_member_of_timeline: validated['timeline UUID'],
                    uuid: validated['timeline item UUID']
                },
                {
                    label: 'Timeline item',
                    deleted_by,
                    select_fields: ['id', 'uuid', 'title', 'is_deleted', 'is_locked', 'locked_by_user'],
                    warn_when_locked: true,
                    /* Timeline items alone do not stamp `updated` on delete;
                     * preserved so recycle-bin ordering does not shift. */
                    touch_updated: false,
                    no_rows_message: 'Delete failed: No rows affected'
                }
            );

            if (already_deleted) {
                return {
                    success: true,
                    already_deleted: true,
                    uuid: validated['timeline item UUID'],
                    affected_rows: 0,
                    message: 'Timeline item record is already deleted'
                };
            }

            this._log_success('Timeline item record deleted successfully', {
                uuid: validated['timeline item UUID'],
                title: existing.title,
                affected_rows,
                deleted_by
            });

            return {
                success: true,
                uuid: validated['timeline item UUID'],
                title: existing.title,
                affected_rows,
                deleted_by,
                message: 'Timeline item record deleted successfully'
            };

        } catch (error) {
            this._handle_error(error, 'delete_timeline_item_record', {
                is_member_of_exhibit,
                is_member_of_timeline,
                item_uuid,
                deleted_by
            });
        }
    }

    /**
     * Gets timeline record count
     * @param {string} uuid - Exhibit UUID
     * @returns {Promise<number>} Count of timeline records
     */
    async get_record_count(uuid) {

        try {

            this._validate_database();
            this._validate_table('timeline_records');

            const exhibit_uuid = this._validate_uuid(uuid, 'exhibit UUID');

            /* Recycled rows are not content: the publish gate must not count them. */
            return await this._get_record_count('timeline_records', {
                is_member_of_exhibit: exhibit_uuid,
                is_deleted: 0
            });

        } catch (error) {
            this._handle_error(error, 'get_record_count', {uuid});
        }
    }

    /*
     * ==================== PUBLISHING / SUPPRESSING ====================
     *
     * The nine publish/suppress methods are generated from PUBLISH_OPS at the
     * top of this file. All nine resolve the result object and throw via
     * _handle_error.
     */

    // ==================== REORDERING ====================

    /**
     * Reorders timelines
     * @param {string} is_member_of_exhibit - Exhibit UUID
     * @param {Object} timelines - Timeline object with uuid and order
     * @param {string} [updated_by=null] - User ID
     * @returns {Promise<Object>} Reorder result
     */
    async reorder_timelines(is_member_of_exhibit, timelines, updated_by = null) {

        try {

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            const result = await this._reorder_items(
                'timeline_records',
                {is_member_of_exhibit: exhibit_uuid},
                timelines
            );

            this._log_success('Timeline reordered', {
                exhibit_uuid,
                uuid: timelines.uuid,
                order: timelines.order
            });

            return result;

        } catch (error) {
            this._handle_error(error, 'reorder_timelines', {
                is_member_of_exhibit
            });
        }
    }

    /**
     * Reorders timeline items
     * @param {string} is_member_of_timeline - Timeline UUID
     * @param {Object} timelines - Timeline item object with uuid and order
     * @param {string} [updated_by=null] - User ID
     * @returns {Promise<Object>} Reorder result
     */
    async reorder_timeline_items(is_member_of_timeline, timelines, updated_by = null) {

        try {

            const timeline_uuid = this._validate_uuid(is_member_of_timeline, 'timeline UUID');

            const result = await this._reorder_items(
                'timeline_item_records',
                {is_member_of_timeline: timeline_uuid},
                timelines
            );

            this._log_success('Timeline item reordered', {
                timeline_uuid,
                uuid: timelines.uuid,
                order: timelines.order
            });

            return result;

        } catch (error) {
            this._handle_error(error, 'reorder_timeline_items', {
                is_member_of_timeline
            });
        }
    }
};

Base_tasks.define_publish_ops(Exhibit_timeline_record_tasks, PUBLISH_OPS);

module.exports = Exhibit_timeline_record_tasks;
