/**

 Copyright 2023 University of Denver

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 */

'use strict';

const LOGGER = require('../../libs/log4');
const Base_tasks = require('./tasks_helper');
const FIELDS = require('../../config/exhibit_fields');

/*
 * Publish/suppress operations, generated by Base_tasks.define_publish_ops.
 * Method names are dispatched by string elsewhere — see that function.
 */
const PUBLISH_OPS = Object.freeze([
    {
        method: 'set_to_publish', table: 'item_records', status: 1,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Item records published', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_to_suppress', table: 'item_records', status: 0,
        scope: 'is_member_of_exhibit', label: 'exhibit UUID',
        log: 'Item records suppressed', log_key: 'exhibit_uuid'
    },
    {
        method: 'set_item_to_publish', table: 'item_records', status: 1,
        mode: 'single', log: 'Item record published',
        contract: 'boolean', record_label: 'item'
    },
    {
        method: 'set_item_to_suppress', table: 'item_records', status: 0,
        mode: 'single', log: 'Item record suppressed',
        contract: 'boolean', record_label: 'item'
    }
]);

/**
 * Object contains tasks used to manage exhibit item records
 * @param DB
 * @param TABLE
 * @type {Exhibit_item_record_tasks}
 */
const Exhibit_item_record_tasks = class extends Base_tasks {

    constructor(DB, TABLE) {
        super(DB, TABLE);
    }

    // Validation helpers, _handle_error, _log_success inherited from Base_tasks

    /**
     * Sets default values for item fields
     * @param {Object} data - Data object to set defaults on
     * @private
     */
    _set_item_defaults(data) {
        this._apply_defaults(data, {
            type: 'item',
            layout: 'media_right',
            wrap_text: 1,
            media_width: 50,
            media_padding: 1,
            is_alt_text_decorative: 0,
            pdf_open_to_page: 1,
            order: 0,
            is_repo_item: 0,
            is_kaltura_item: 0,
            is_embedded: 0,
            is_published: 0,
            is_locked: 0,
            locked_by_user: 0,
            locked_at: null,
            is_deleted: 0,
            owner: 0,
            margins: 'medium',
            text_alignment: 'left'
        });
    }

    /**
     * Gets the appropriate table name for a given type
     * @param {string} type - Item type
     * @returns {string} Table name
     * @private
     */
    _get_table_for_type(type) {
        const type_map = {
            'item': 'item_records',
            'grid': 'grid_records',
            'heading': 'heading_records',
            'timeline': 'timeline_records',
            'standard_item': 'item_records',
            'grid_item': 'grid_item_records',
            'timeline_item': 'timeline_item_records',
            'vertical_timeline': 'timeline_records'
        };

        const normalized_type = type.toLowerCase().trim();
        const table_name = type_map[normalized_type];

        if (!table_name) {
            throw new Error(`Invalid item type: ${type}`);
        }

        return table_name;
    }

    // _update_publish_status, _update_single_publish_status, _reorder_items inherited from Base_tasks

    // ==================== ITEM RECORDS ====================

    /**
     * Creates a new item record
     * @param {Object} data - Item record data
     * @param {string} [created_by=null] - User ID creating the record
     * @returns {Promise<Object>} Created item record
     */
    async create_item_record(data, created_by = null) {

        try {

            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('item_records');

            // Validate required fields
            const validated = this._validate_uuids({
                [data.uuid]: 'item UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            this._validate_string(data.item_type, 'item_type');

            // Build record with defaults
            const record_data = {
                uuid: validated['item UUID'],
                is_member_of_exhibit: validated['exhibit UUID'],
                item_type: data.item_type.trim(),
                mime_type: data.mime_type.trim() || null,
                thumbnail: data.thumbnail || null,
                thumbnail_media_uuid: data.thumbnail_media_uuid || null,
                caption: data.caption || null,
                media: data.media || null,
                media_uuid: data.media_uuid || null,
                text: data.text || null,
                description: data.description || null,
                alt_text: data.alt_text || null,
                item_subjects: data.item_subjects || null,
                styles: data.styles || null,
                created_by: created_by || data.created_by || null,
                updated_by: created_by || data.updated_by || null
            };

            // Set defaults
            this._set_item_defaults(record_data);

            /*
             * Override defaults with provided values. Standard items do not
             * sanitize against a create whitelist — they build the record
             * above and let the request choose from this subset, which lives
             * in config/exhibit_fields.js with every other create surface.
             */
            FIELDS.ITEM_CREATE_OPTIONAL_FIELDS.forEach(field => {
                if (data[field] !== undefined) {
                    record_data[field] = data[field];
                }
            });

            // Create in transaction
            const created_record = await this._insert_and_fetch('item_records', record_data);

            this._log_success('Item record created successfully', {
                uuid: validated['item UUID'],
                item_type: data.item_type.trim(),
                created_by
            });

            return {
                success: true,
                uuid: validated['item UUID'],
                id: created_record.id,
                record: created_record,
                message: 'Item record created successfully'
            };

        } catch (error) {
            this._handle_error(error, 'create_item_record', {
                uuid: data?.uuid,
                created_by
            });
        }
    }

    /**
     * Gets item records by exhibit
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @returns {Promise<Array>} Array of item records
     */
    async get_item_records(is_member_of_exhibit) {

        try {

            this._validate_database();
            this._validate_table('item_records');
            this._validate_table('media_library_records');

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            const items = await this._with_media_library(
                this.DB(this.TABLE.item_records), 'item_records', 'list'
            )
                .where({
                    [`${this.TABLE.item_records}.is_member_of_exhibit`]: exhibit_uuid,
                    [`${this.TABLE.item_records}.is_deleted`]: 0
                })
                .orderBy(`${this.TABLE.item_records}.order`, 'asc')
                .timeout(this.QUERY_TIMEOUT);

            this._log_success('Item records retrieved successfully', {
                is_member_of_exhibit: exhibit_uuid,
                count: items.length
            });

            return items || [];

        } catch (error) {
            this._handle_error(error, 'get_item_records', {
                is_member_of_exhibit
            });
        }
    }

    /**
     * Gets a single item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} uuid - The item UUID
     * @returns {Promise<Object|null>} Item record or null
     */
    async get_item_record(is_member_of_exhibit, uuid) {

        try {

            this._validate_database();
            this._validate_table('item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [uuid]: 'item UUID'
            });

            const result = await this._with_media_library(
                this.DB(this.TABLE.item_records), 'item_records', 'list'
            )
                .where({
                    [`${this.TABLE.item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.item_records}.uuid`]: validated['item UUID'],
                    [`${this.TABLE.item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            return result || null;

        } catch (error) {
            LOGGER.module().error('Failed to get item record: ' + error.message);
            return null;
        }
    }

    /**
     * Gets an item record for editing and locks it
     * @param {string|number} uid - User ID
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} uuid - The item UUID
     * @returns {Promise<Object|null>} Item record with lock status
     */
    async get_item_edit_record(uid, is_member_of_exhibit, uuid) {

        try {

            this._validate_database();
            this._validate_table('item_records');
            this._validate_table('media_library_records');

            this._validate_user_id(uid);

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [uuid]: 'item UUID'
            });

            const record = await this._with_media_library(
                this.DB(this.TABLE.item_records), 'item_records', 'edit'
            )
                .where({
                    [`${this.TABLE.item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.item_records}.uuid`]: validated['item UUID'],
                    [`${this.TABLE.item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Item record not found', validated);
                return null;
            }

            return await this._lock_for_edit(record, uid, 'item_records', {
                label: 'Item',
                uuid: validated['item UUID']
            });

        } catch (error) {
            this._handle_error(error, 'get_item_edit_record', {
                uid,
                uuid
            });
        }
    }

    /**
     * Gets an item record with media library metadata for read-only details view.
     * Same query as get_item_edit_record but does NOT lock the record.
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} uuid - The item UUID
     * @returns {Promise<Object|null>} Item record with media metadata or null
     */
    async get_item_details_record(is_member_of_exhibit, uuid) {

        try {

            this._validate_database();
            this._validate_table('item_records');
            this._validate_table('media_library_records');

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [uuid]: 'item UUID'
            });

            const record = await this._with_media_library(
                this.DB(this.TABLE.item_records), 'item_records', 'edit'
            )
                .where({
                    [`${this.TABLE.item_records}.is_member_of_exhibit`]: validated['exhibit UUID'],
                    [`${this.TABLE.item_records}.uuid`]: validated['item UUID'],
                    [`${this.TABLE.item_records}.is_deleted`]: 0
                })
                .first()
                .timeout(this.QUERY_TIMEOUT);

            if (!record) {
                this._log_success('Item record not found', validated);
                return null;
            }

            this._log_success('Item details record retrieved successfully', {
                uuid: validated['item UUID'],
                is_member_of_exhibit: validated['exhibit UUID']
            });

            return record;

        } catch (error) {
            this._handle_error(error, 'get_item_details_record', {
                is_member_of_exhibit,
                uuid
            });
        }
    }

    /**
     * Updates an item record
     * @param {Object} data - Item data to update
     * @param {string} [updated_by=null] - User ID performing the update
     * @returns {Promise<Object>} Update result
     */
    async update_item_record(data, updated_by = null) {

        try {
            this._validate_data_object(data);
            this._validate_database();
            this._validate_table('item_records');

            const validated = this._validate_uuids({
                [data.uuid]: 'item UUID',
                [data.is_member_of_exhibit]: 'exhibit UUID'
            });

            /*
             * Standard items used to hand-roll this with a hasOwnProperty loop
             * over the whitelist, and to re-SELECT the row afterwards for a
             * `record` key nothing read. Both are gone: the shared helper
             * sanitizes (so prototype keys are dropped and rejected fields are
             * logged, like every sibling) and returns the common envelope.
             */
            return await this._update_scoped(
                'item_records',
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['item UUID']
                },
                data,
                {
                    allowed_fields: FIELDS.ITEM_UPDATE_FIELDS,
                    skip_fields: ['uuid', 'is_member_of_exhibit'],
                    label: 'Item',
                    uuid: validated['item UUID'],
                    updated_by,
                    /* Standard items are the one type that stamps `updated` here. */
                    touch_updated: true,
                    no_rows_message: 'Failed to update item record: No rows affected'
                }
            );

        } catch (error) {
            this._handle_error(error, 'update_item_record', {
                uuid: data?.uuid,
                updated_by
            });
        }
    }

    /**
     * Soft deletes an item record
     * @param {string} is_member_of_exhibit - The exhibit UUID
     * @param {string} item_id - The item UUID
     * @param {string} type - The item type
     * @param {string} [deleted_by=null] - User ID performing the deletion
     * @returns {Promise<Object>} Delete result
     */
    async delete_item_record(is_member_of_exhibit, item_id, type, deleted_by = null) {

        try {

            this._validate_database();

            const validated = this._validate_uuids({
                [is_member_of_exhibit]: 'exhibit UUID',
                [item_id]: 'item UUID'
            });

            this._validate_string(type, 'item type');

            // Get table for type
            const table_name = this._get_table_for_type(type);
            this._validate_table(table_name);

            /* `type` is the caller's word for the record ("grid item", "heading"),
             * so the not-found message is title-cased from it rather than fixed. */
            const {already_deleted, affected_rows} = await this._soft_delete_scoped(
                table_name,
                {
                    is_member_of_exhibit: validated['exhibit UUID'],
                    uuid: validated['item UUID']
                },
                {
                    label: type,
                    deleted_by,
                    not_found_message: `${type.charAt(0).toUpperCase() + type.slice(1)} record not found`,
                    no_rows_message: `Failed to delete ${type} record: No rows affected`
                }
            );

            if (already_deleted) {
                return {
                    success: true,
                    already_deleted: true,
                    uuid: validated['item UUID'],
                    type,
                    message: `${type} record was already deleted`
                };
            }

            this._log_success('Record deleted successfully', {
                type,
                uuid: validated['item UUID'],
                deleted_by
            });

            // Reorder
            const new_order = await this.HELPER.reorder(validated['exhibit UUID'], this.DB, this.TABLE);
            const new_order_applied = await this.HELPER.apply_reorder(validated['exhibit UUID'], new_order, this.DB, this.TABLE);

            if (new_order_applied.success === false) {
                LOGGER.module().error('Failed to reorder records', new_order_applied);
            }

            return {
                success: true,
                uuid: validated['item UUID'],
                type,
                affected_rows,
                deleted_by,
                message: `${type} record deleted successfully`
            };

        } catch (error) {
            this._handle_error(error, 'delete_item_record', {
                is_member_of_exhibit,
                item_id,
                type,
                deleted_by
            });
        }
    }

    /**
     * Gets the count of item records for an exhibit
     *
     * Errors THROW. This used to swallow them and return 0, alone among the
     * four get_record_count implementations; since all four run under one
     * Promise.all in the exhibit publish gate, a swallowed error here could
     * only ever have fed the gate a wrong count (DRY review cluster S6).
     *
     * @param {string} uuid - The exhibit UUID
     * @returns {Promise<number>} Count of item records
     */
    async get_record_count(uuid) {

        try {

            this._validate_database();
            this._validate_table('item_records');

            const exhibit_uuid = this._validate_uuid(uuid, 'exhibit UUID');

            /* Recycled rows are not content: the publish gate must not count them. */
            return await this._get_record_count('item_records', {
                is_member_of_exhibit: exhibit_uuid,
                is_deleted: 0
            });

        } catch (error) {
            this._handle_error(error, 'get_record_count', {uuid});
        }
    }

    /*
     * ==================== PUBLISHING / SUPPRESSING ====================
     *
     * set_to_publish, set_to_suppress, set_item_to_publish and
     * set_item_to_suppress are generated from PUBLISH_OPS at the bottom of
     * this file. Contracts are unchanged: the two exhibit-scoped methods
     * resolve the result object and throw; the two single-item methods
     * resolve true and log-and-resolve false on error.
     */

    // ==================== REORDERING ====================

    /**
     * Reorders items
     * @param {string} is_member_of_exhibit - Exhibit UUID
     * @param {Object} item - Item object with uuid and order
     * @returns {Promise<boolean>} Reorder success status
     */
    async reorder_items(is_member_of_exhibit, item) {

        try {

            const exhibit_uuid = this._validate_uuid(is_member_of_exhibit, 'exhibit UUID');

            await this._reorder_items(
                'item_records',
                {is_member_of_exhibit: exhibit_uuid},
                item
            );

            this._log_success('Item reordered', {
                exhibit_uuid,
                uuid: item.uuid,
                order: item.order
            });

            return true;

        } catch (error) {
            LOGGER.module().error('Failed to reorder item: ' + error.message);
            return false;
        }
    }
};

Base_tasks.define_publish_ops(Exhibit_item_record_tasks, PUBLISH_OPS);

module.exports = Exhibit_item_record_tasks;
